### ISSUE TITLE
Error: Shared IPC Compositor Connect Failed (306)

### ISSUE THREAD

**Issue by Kalman98** [ValveSoftware/SteamVR-for-Linux#16]
#### Your system information
* Steam client version (build number or date): Built: Feb 23 2017, at 00:38:08
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Graphics driver version (run nvidia-settings): 375.27.10
* Gist for SteamVR System Information: https://gist.github.com/Kalman98/af18cfc4643c1cb84fac2e3df60df984
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

vrclient_steam.txt: https://gist.github.com/Kalman98/011ea211060355416c7c97fd3dd23ad7
vrclient_steamvr_room_setup.txt: https://gist.github.com/Kalman98/6f2bf09e5d4d76c254e4f9c2944a6317
vrclient_steamvr_tutorial.txt: https://gist.github.com/Kalman98/248c71432a61dcbb5e441418f6e62286
vrclient_vrcompositor.txt: https://gist.github.com/Kalman98/23675ea1074d846ef0ff78dd87a41432
vrclient_vrmonitor.txt: https://gist.github.com/Kalman98/48cc8160248e3c4c32e759c0d801fe33
vrcompositor.txt: https://gist.github.com/Kalman98/9327d1b8506658cf7a552759e43c342a
vrmonitor.txt: https://gist.github.com/Kalman98/88d22643c8db447b80864000592b5429
vrserver.txt: https://gist.github.com/Kalman98/1286883ba42ca6ce6f96a0c51d8c8547

#### Please describe your issue in as much detail as possible:
I am using the null driver.
My steamvr.vrsettings config: https://gist.github.com/Kalman98/c069ac11efe97a720c1484463e5124bb

It gives me the error stated.

#### Steps for reproducing this issue:
1. Enable null driver.
2. Start SteamVR.

**Comment by tizzir** [comment]
Are you launching steam with STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0?

I will get error 306 on my system unless I launch it with this set.

**Comment by Kalman98** [comment]
@tizzir I just tried that - same outcome.

**Comment by michaellarabel** [comment]
I had/have this issue as well on an Ubuntu 16.10 box with 375.27.10 and the latest Steam/SteamVR betas as well. Using STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 ended up fixing it, but still appears to be rather flakey.

**Comment by ParkerMc** [comment]
@michaellarabel the command to run steam with that is `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` right?

**Comment by tizzir** [comment]
@ParkerMc Yep, that should do it.

**Comment by ParkerMc** [comment]
I think this may be something with amd cpu(s) since @Kalman98 uses one and so dose @asannes form #26 that seems to be the same issue. Just trying to draw some lines let me know if I am wrong.

**Comment by Kalman98** [comment]
@ParkerMc and anyone else who may need it, here is my CPU information:

https://gist.github.com/Kalman98/718b93b537f3fa8711e5254cf9f47521

Use it wisely.

**Comment by voidplayer** [comment]
I also have this issue and I have intel and nvidia, so im not sure is related to the cpu being amd

Im stuck in built 24 feb, so not sure if this still happens with the latest version (supposedly march 1st)

**Comment by FictionX** [comment]
I had the 306 error as well - and STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 didn't fix it.
Uninstalling libvulkan1 (using the package manager) solved the problem for me on Ubuntu 16.10.

Now, if I need to run something "outside Steam", I use **_~/.steam/steam/ubuntu12_32/steam-runtime/run.sh /path/to/executable_**

**Comment by voidplayer** [comment]
`dpkg -l |grep vulkan` returns nothing here and `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` didnt fix it here either

**Comment by DiThi** [comment]
Getting the same issues with intel, nvidia and ubuntu 16.04. Tried all the above. Should I update to 16.10?

**Comment by voidplayer** [comment]
Not sure what fixed it, but this bug does no longer affect me. I dint uninstall anything, nor I use that env variable

**Comment by spencerh-b** [comment]
I have tried every solution I can find on the internet, but nothing seems to work, running ubuntu 14.04, Nvidia 1080 GTX with newest of drivers. Tried starting with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES = 0 steam` to no avail. 
The vive works on the windows partition of the computer.

**Comment by kisak-valve** [comment]
Hello @spencerh-b, exactly what version of the nvidia driver are you using? Only 375.27.10 and 375.27.13 from the vulkan dev beta are compatible at this time, not the latest driver.

**Comment by Conzar** [comment]
I am having this problem.   
```
dpkg -l |grep nvidia-375
ii  nvidia-375  375.27.13-0ubuntu0~gpu16.04.1 amd64  NVIDIA binary driver - version 375.27.13
```

**Comment by spencerh-b** [comment]
@kisak-valve I currently 375.27.13

**Comment by DiThi** [comment]
Make sure you all have Steam client Beta. If you don't, uninstall SteamVR before switching Steam.

**Comment by spencerh-b** [comment]
Is anyone able to tell me what a compositor is? As well, does anyone have any documentation as to why this error is thrown?

**Comment by spencerh-b** [comment]
Update: Purging all drivers and reinstalling the latest one seemed to do the trick, if this doesn't work. I actually fixed the issue while attempting to install unreal engine, could be that a missing dependency was fixed

**Comment by DiThi** [comment]
> Is anyone able to tell me what a compositor is?

In the old days, games drew directly to the headset screen. That wasn't very practical because only one thing could draw at a time, and there couldn't be an overlay to close one app and open another, chaperone, notifications, etc.

The compositor does that by taking a texture with the frame from the game. Also it simplifies the development pipeline since games themselves don't have to worry about distortion, reprojection, and a myriad of other things such as USB input. In a way, the compositor is one part of the HMD "driver".

**Comment by MrMinimal** [comment]
Getting this 306 error with an Intel CPU and an AMD RX 480 using the latest 17.10-401251 driver.
Even though I start Steam with this command, it has not fixed the error for me:
```
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
```

My setup is [https://gist.github.com/MrMinimal/6c1d35595354f624700fb738bd6977da](https://gist.github.com/MrMinimal/6c1d35595354f624700fb738bd6977da)
* Ubuntu 16.10 64bit - 4.8.0-46-generic
* Intel i7 6700K
* RX 480 - AMDGPU driver 17.10-401251


Also getting the following in the kernel log:
```
vrcompositor[4992]: segfault at 26d3660 ip 00000000026d3660 sp 00007ffd94feca58 error 15
```
My terminal after starting SteamVR:
[https://gist.github.com/MrMinimal/15dc98b8f95f15f68f6199ab95787ac2](https://gist.github.com/MrMinimal/15dc98b8f95f15f68f6199ab95787ac2)

@michaellarabel Have you had experience with AMD GPUs for VR?

**Comment by kisak-valve** [comment]
Hello @MrMinimal, my understanding is that amdgpu-pro does not support the experimental vulkan extensions that are required for SteamVR. Mesa's next release and git master should have support for those extensions. [Oibaf's PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) and [Padoka's PPA](https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa) should have sufficiently new builds of mesa, however, you may encounter random regressions since these are development builds.

**Comment by alex9099** [comment]
I'm with same problem on nvidia, the most relevant error i see is 'Xlib:  extension "NV-GLX" missing on display ":0".' but i'm not sure if it is the cause of the problem, if needed i post the logs (i'm on arch linux)

**Comment by alex9099** [comment]
It seems like i got some success using nvidia-xrun, but it is pretty slow :( not sure what to do to speed up

**Comment by alex9099** [comment]
For some reason it does not work again ... maybe some upgrade?

**Comment by Conzar** [comment]
I'm getting the same error again.

**Comment by lubosz** [comment]
I am getting the error on 2 laptops with 2 different Vives. One is nvidia, the other intel, same error.
Using SteamVR or Steam beta does not fix it.
Rebooted the headsets, reconnected everything, nothing helps. Don't have the issue on my desktop.

**Comment by jewalker** [comment]
I'm getting this error on a Dell Precision T7600 desktop machine with an NVIDIA Quadro 4000 running RHEL 7.3 with the MATE desktop environment and the latest NVIDIA driver (381.22). This driver is the recommended driver as listed in the Readme. I do not have native vulkan drivers and I did launch steam (and vrstartup.sh) with STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0.

**Comment by kisak-valve** [comment]
Hello @jewalker, please re-read the Readme.md, it now says that the current vulkan dev branch - nvidia 381.26.08 is required and the mainline driver including 381.22 is not supported anymore.

**Comment by jewalker** [comment]
Thanks. The Readme was updated yesterday after I did my testing.

**Comment by ParkerMc** [comment]
I just got a new computer and now I am getting this issue, here is the gdb output. I checked the udev rules and they are there. I was trying to use the null driver if that matters.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7489f00 in vkGetPhysicalDeviceDisplayPropertiesKHR ()
   from /home/******/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libvulkan.so.1
(gdb) bt full
#0  0x00007ffff7489f00 in vkGetPhysicalDeviceDisplayPropertiesKHR ()
   from /home/******/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libvulkan.so.1
No symbol table info available.
#1  0x0000000000470e06 in vr::CHmdWindowSDL::CreateDirectModeSurface(unsigned int, unsigned int) ()
No symbol table info available.
#2  0x0000000000472dde in vr::CHmdWindowSDL::CHmdWindowSDL(vr::CHmdDistort*, int, int, unsigned int, unsigned int) ()
No symbol table info available.
#3  0x0000000000448e92 in vr::CHmdDistort::Initialize(vr::CVRNotificationManager*, CVRSharedState*, void*, bool) ()
No symbol table info available.
#4  0x0000000000476402 in CVRCompositor::Init() ()
No symbol table info available.
#5  0x0000000000479a35 in RealMain(unsigned int, ParsedArguments_t&) ()
No symbol table info available.
#6  0x000000000044036a in main ()
No symbol table info available.
```

**Comment by Kalman98** [comment]
I have switched to Arch Linux somewhere in the middle of all of this and am now using a GTX 1050 GPU. Besides that my PC remains the same.

Opting out of SteamVR beta now seems to make it run correctly. Maybe there's a driver issue with SteamVR beta?

**Comment by jewalker** [comment]
I updated my machine with an NVIDIA K5000 and updated to the 384.47 version of the driver. I am no longer getting the 306 error, but I am still getting a screen flash when starting SteamVR, and I can't interact properly with the SteamVR gui. Every time I click on something in the gui my screen goes black. Clicking anywhere off of the gui restores my screen. It is evident that the gui is responding, I just can't see what it's doing. I suspect this has something to do with the MATE desktop environment and compositing settings. We occasionally see similar problems with Maya's hotbox. I was able to run Room Setup and the SteamVR tutorial, but the tutorial froze about 75% through.

**Comment by Balderick** [comment]
@jewalker  I see what you are describing on windows.   Sometimes steamvr crashes when this happens but mostly doesn't.   Sometimes steamvr never actually quits.  I notice it when my steam controller refuses to work as expected on desktop (sc always been bug ridden in steamvr).  Sometimes system mouse does not even work in steamvr status dropdown menu and task manager is needed to kill steamvr

**Comment by rhaleblian** [comment]
Had this issue, using NVIDIA's Vulkan dev driver as stated in README resolved it.
Got through Room Setup and the Tutorial, now tackling UE4 integration.

**Comment by madrang** [comment]
I would love to try the Vulkan dev driver, but i need the NVIDIA CUDA Deep Neural Network library and Ubuntu is trying to remove too many dependencies when i move to those drivers and i'm worried that cudnn will stop working....
https://developer.nvidia.com/cudnn

**Comment by Kalman98** [comment]
Well, it works in the latest version of SteamVR. Thanks, guys!

**Comment by rux616** [comment]
I hate to say this, but I'm getting the same error, using both the current beta and release.

__OS:__ Ubuntu 16.04
__Nvidia Driver:__ 384.90
__Steam Package Versions:__ 1508910373
__SteamVR Version (Release):__ 1507941678

I've also tried running the Steam client from the command line preceded by `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` and it still doesn't work.

I've dumped the stdout spam from running the Steam client [to a gist](https://gist.github.com/rux616/66fdb5eb2582123f4e17c445fd500650) in the hopes it will help.

**Comment by spencerh-b** [comment]
@rux616 make sure that you are using the Nvidia Driver in your settings. If the driver is selected my next suggestion would be to make sure that you don't have multiple drivers installed after I purged my nvidia drivers and reinstalled the one I wanted I was able to get this to work.

**Comment by johnv-valve** [comment]
Also if you can create a system report (from the vrmonitor menu) that will be more helpful than the stdout spam.

**Comment by rux616** [comment]
I have since purged and reinstalled my Nvidia drivers, ran the system report, and [uploaded it here](https://gist.github.com/rux616/7bf3e355f54f9005b82730e977cabb86).

I noticed under the vrcompositor.txt logs that it was saying something about not being able to create Vulkan resources, but I'm not sure why that would be the case, since the 384-series driver supposedly has them integrated.

Any thoughts?

**Comment by spencerh-b** [comment]
@rux616 very strange. I have been using the 375 and have not run into these issues so I am unable to help with your exact situation, sorry I cannot be more help.

**Comment by Balderick** [comment]
@rux616 
Does adding '"direct mode" : true` to the steamvr section of your steamvr.vrsettings config file help?
Looks like steamvr is not seeing your nvidia drivers as supporting direct mode.  Getting direct mode working may help you out.

Does deleting ubuntus native libvulkan package like what is mentioned in a comment above help steamvr use the correct nvidia vulkan libraries?   The comment also highlights this worked where using `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` does not work.

**Comment by johnv-valve** [comment]
What is the output from vulkaninfo? (may have to install the vulkan-utils package if you haven't already)

**Comment by rux616** [comment]
First of all, I wanted to thank you all @spencerh-b, @Balderick, and @johnv-valve for your help thus far.

Second, on to more findings. @Balderick I don't actually seem to have a `steamvr.vrsettings` config file anywhere that I can find. I have looked both in `~/.steam/steam/config` and `~/.local/share/Steam/config`, in addition to doing a full search on all directories on my system just to make sure. Where does this file typically live, and what are the default settings? Also, I removed the `libvulkan1` package from my system, rebooted, and still got the 306 error.

Lastly, @johnv-valve, I installed the `vulkan-utils` package (which brings along `libvulkan1` as a dependency) and ran `vulkaninfo` as requested.

```log
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.61

INFO: [loader] Code 0 : Found manifest file /home/<username>/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file /home/<username>/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json, version "1.0.0"
INFO: [loader] Code 0 : Meta-layer VK_LAYER_LUNARG_standard_validation all 0 component layers appear to be valid.
INFO: [loader] Code 0 : Found ICD manifest file /usr/share//vulkan/icd.d/nvidia_icd.json, version "1.0.0"
ERROR: [loader] Code 0 : loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD libGL.so.1 failed.
Cannot create Vulkan instance.
/build/vulkan-d8F03h/vulkan-1.0.61.1+dfsg1/demos/vulkaninfo.c:698: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

If I am interpreting this correctly, it looks like for whatever reason something's up with my `libGL.so.1`? (If it is using the file located in `/usr/lib/nvidia-384`, it's a symbolic link to `libGL.so.1.0.0`.)

**Comment by Balderick** [comment]
Whenever you make changes in steamvr settings (from steamvr monitor GUI) a config file is made.  You will find it in your steam installs config dir.   On a clean steam or steamvr install there is no steamvr.vrsettings file created and so not finding one is default / expected behaviour.

Going by what vulkaninfo gave you, it is telling you either you need to reinstall GPU driver or use a different GPU driver.  I.e. `VK_ERROR_INCOMPATIBLE_DRIVER`

**Comment by rux616** [comment]
I've added the `"directMode" : true` line to the `steamvr.vrsettings` file to no avail.

Also, the GPU driver I'm using is of the recommended series from the SteamVR for Linux readme, and is installed from the graphics driver ppa also as recommended.

The Nvidia kernel modules are currently loaded.

```log
$ lsmod | grep nvidia
nvidia_uvm            671744  0
nvidia_drm             45056  1
nvidia_modeset        843776  6 nvidia_drm
nvidia              13004800  693 nvidia_modeset,nvidia_uvm
drm_kms_helper        151552  1 nvidia_drm
drm                   352256  4 nvidia_drm,drm_kms_helper
```

**Comment by johnv-valve** [comment]
Your problem is your nvidia vulkan installation is broken. Until vulkaninfo works there is no point in messing with any SteamVR settings (and that one doesn't do anything anyway)

**Comment by Balderick** [comment]
@johnv-valve Why does that api switch exist if it does nothing anyway? Is another issue but would like to ask What does rux616 have to do to get steamvr working as expected?

**Comment by rux616** [comment]
Okay, I purged the Nvidia 384.90 driver from my system and went with the 381.22 driver instead. `vulkaninfo` [now doesn't seem to have any problems](https://gist.github.com/rux616/bccfcdf81e2370f04530f52e0e2366b9), but SteamVR still refuses to start up, with both release and beta branches getting the 306 error.

I've created another [system report](https://gist.github.com/rux616/5f9a44fd0452cbaf34994f21458565c2), which seems to show things as working, until they don't.

**Comment by johnv-valve** [comment]
You need Nvidia 384.69 or greater, 381.22 will not work. You need vulkan to be working with that driver. I do not know what is wrong with your system that this is not working for you, but until you get that fixed SteamVR is not going to work.

@Balderick  - that switch works on Windows but on Linux we always use direct mode if it is available (and it should be available if you have the right nvidia driver)

**Comment by rux616** [comment]
I switched back to the 384.90 driver and was still having issues, but found the cause. Somehow the Nvidia Vulkan json file at `/usr/share/vulkan/icd.d/nvidia_icd.json` was messed up and had `"library_path": "libGL.so.1"` instead of `"library_path": "libGLX_nvidia.so.0"`, as detailed [here](https://askubuntu.com/a/967910). I changed that, and `vulkaninfo` now runs and is happy, and SteamVR starts up without throwing the 306 error. Now if I can only get the HMD to actually display things, I'll be good. But that's a different problem and I won't clutter this issue with it.

Thanks again to @johnv-valve and @Balderick for your help.

**Comment by yaomtc** [comment]
I'm getting this error with AMD (RX 580, Linux 4.15.5, Mesa 17.3.5). Does it have to do with the desktop compositor not being disabled? Couldn't find a way to do that in Gnome, I tried using "Gnome on Xorg" and "Gnome Classic" (as well as Budgie, initially) and nothing changes. I have the udev rules set up, and I've tried using a different USB port. I have the monitor disabled in the Displays section of Gnome Control Center.

**Comment by yaomtc** [comment]
I thought some differences in Solus might have been the issue, so I installed Ubuntu, since it's Steam's officially supported desktop Linux distro. Well, that didn't help at all, I get the exact same results. Here's a report, and vulkaninfo output.

[steamvr-report.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/1778033/steamvr-report.txt)
[vulkaninfo.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/1778034/vulkaninfo.txt)

**Comment by Zamundaaa** [comment]
So I had this error too. The issue all came down to not having the package mesa-vulcan-drivers installed (pretty dumb mistake, but you wouldn't find it from that error code if you hadn't suggested running vulkaninfo...). Installing it fixed the error and I seem to get a borderless window on the vive now (if extending the desktop to it, if not I just got it on my other screens, not very nice). I'm running Kubuntu 18.04 with an upgraded kernel 4.17.9 with a RX 580. The room setup wanted to start then but I didn't let it finish as it's pretty late now
