### ISSUE TITLE
GetControllerState from FnTable always zeroes VRControllerState_t struct

### ISSUE THREAD

**Issue by valentindavid** [ValveSoftware/SteamVR-for-Linux#35]
#### Your system information
* Steam client version (build number or date): 1488992261
* Distribution (e.g. Ubuntu): Gentoo
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: https://gist.github.com/valentindavid/64b4ee1ebdca82af92cdf6d4f0bedb10
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

`GetControllerState` from `FnTable:IVRSystem_015` (C API) always return with a zeroed `VRControllerState_t` struct when `GetControllerState` from `IVRSystem_015` returns with a correct `VRControllerState_t` struct.

This is a problem for ViveCraft for example that uses the C API through JOpenVR. No button on the controllers work.

Here is an example of program. When running, hold buttons. It should then show non zero values. But it is always 0.

```
#include <openvr.h>
#include <openvr_capi.h>
#include <iostream>
#include <chrono>
#include <thread>

int main() {
  vr::HmdError err;
  auto ignored = vr::VR_Init(&err, vr::VRApplication_Scene);

  auto vrsystem = (VR_IVRSystem_FnTable*)vr::VR_GetGenericInterface("FnTable:IVRSystem_015", &err);

  if (err) {
    std::cerr << vr::VR_GetVRInitErrorAsSymbol(err) << "\n";
    return 1;
  }
  while (true) {
    for (vr::TrackedDeviceIndex_t i = 0; i < vr::k_unMaxTrackedDeviceCount; ++i) {
      VRControllerState_t state;
      if (vrsystem->GetControllerState(i, &state, sizeof(state))) {
	std::cerr << state.ulButtonPressed << "\n";
      }
    }
    std::this_thread::sleep_for(std::chrono::seconds(1));
  }
  return 0;
}
```

**Comment by valentindavid** [comment]
Also note, you need to fix the ``openvr_capi.h`` to compile with GCC: ``__stdcall`` is not valid in GCC.

**Comment by valentindavid** [comment]
This is an alignment problem. `sizeof(VRControllerState_t)` is 64, when `sizeof(vr::VRControllerState_t)` is 60. There are 4 bytes missing between the two first fields.

**Comment by johnv-valve** [comment]
openvr_capi.h needs the same #pragma pack(push, 4) that openvr.h has.

**Comment by johnv-valve** [comment]
this is fixed in the current openvr SDK.

**Comment by kazoo-kmt** [comment]
I still have this issue. Not only the controller state, but also the data comes with pollNextEvent returns zero. This is similar question, but there are no answer yet.
http://steamcommunity.com/app/250820/discussions/5/1368380934264788570/

**Comment by Dmytry** [comment]
It's not fixed. On Linux 64 bit, the size of C struct is 64 and the size of C++ struct is 60 , and looking at the sources, we have https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_capi.h#L1336  no pack pragma around it (padding of 4 after unPacketNum because the subsequent value is 8 byte sized) and https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L890  has pack 4 pragma around it, but only for linux and mac.

**Comment by ChristophHaag** [comment]
Can confirm, the C header is still missing pragma pack. I know GetControllerState() is deprecated, but still...

**Comment by Plagman** [comment]
I believe this is fixed and will be out in the next SDK.
