### ISSUE TITLE
Unreal 5.0.0 doesn't detect HTC Vive Pro Eye / SteamVR in Ubuntu: "VR Preview" greyed out

### ISSUE THREAD

**Issue by Bengt** [ValveSoftware/SteamVR-for-Linux#509]
When I start Unreal Engine 5, the button "VR Preview" in the play mode menu is greyed out.

1. Start the VR Template Project in Unreal Engine 5
2. Click on the play mode menu
3. See the greyed-out "VR Preview" button

**Expected behavior**

The "VR-Preview" button should be selectable and the VR play mode should work.

**System Information (please complete the following information):**

- Distribution: Ubuntu 20.04 LTS
- SteamVR version: 1.21.12
- Steam client version: March 14th, 2022
- Opted into Steam client beta: No
- Graphics driver version: Mesa 21.2.6 (LLVM 12.0.0)
- [Gist for SteamVR System Information](https://gist.github.com/Bengt/8f718c7274f27e070b79095a270a1c72)

**Screenshots**

![unreal_engine_5_vr_playmode](https://user-images.githubusercontent.com/11575/162447169-40fde365-b719-4917-9e4f-8114a5cb05e8.png)

**Additional context**

- I already tried starting SteamVR before launching Unreal Engine, but that does not help.
- I ensured that all base stations and controllers are active in SteamVR before and while starting Unreal Engine, but that did not help.

There has been a seemingly similar issue in the past, namely #55.

**Comment by Bengt** [comment]
I am trying to build the project for Linux natively using the "Project Launcher" now.

**Comment by Bengt** [comment]
When I run from the steam runtime environment, with SteamVR "Standing by", the "VR Preview" button is still greyed out. Specifically, I ran this command with a fresh build of Unreal Editor 5 and the VR template project:

```bash
~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./Engine/Binaries/Linux/UnrealEditor \
'/home/bengt/Downloads/DFKI/git.ni.dfki.de/VR/VR.Frontend_5.0/VR_Frontend_5_0/VR_Frontend.uproject' \
-opengl4 \
-sm5
```

**Comment by Bengt** [comment]
The means, [the answer closing former issue](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/55#issuecomment-308261859) does not work for me. How can I debug this further?

**Comment by Bengt** [comment]
I just retested this using a fresh installation, that I was doing anyway:
Using Ubuntu Server 20.04 + all updates + the X-SWAT PPA does not work either.

**Comment by Bengt** [comment]
I am trying to install AMD's Vulkan implementation:

```
amdgpu-install --vulkan=amdvlk
```

**Comment by Bengt** [comment]
After installing the amdgpu-pro Vulkan driver, like so:

```
amdgpu-install --usecase=graphics,opencl,rocm --opencl=rocr --vulkan=pro
```

I still get the same error:

```
[2022.04.12-13.05.09:993][  0]Message dialog closed, result: Ok, title: WARNING: Known issues with graphics driver, text: The installed version of the AMD graphics driver has known issues.
Please install either the latest or the recommended driver version.

https://www.amd.com/en/support

Radeon RX Vega
Installed: 2.0.207
Recommended: 21.2.6
```

I also noticed another error:

```
[2022.04.12-13.09.10:448][  0]LogEngine: Initializing Engine...
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to determine active runtime file path for this environment
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
[2022.04.12-13.09.10:460][  0]LogHMD: Failed to enumerate extensions. Please check that you have a valid OpenXR runtime installed.
```

So, to install an OpenXR runtime, I installed Monado's build requirements:

```
sudo apt install --yes meson ninja-build build-essential git wget unzip cmake meson ninja-build libeigen3-dev curl patch python3 pkg-config libx11-dev libx11-xcb-dev libxxf86vm-dev libxrandr-dev libxcb-randr0-dev libvulkan-dev glslang-tools libglvnd-dev libgl1-mesa-dev ca-certificates libusb-1.0-0-dev libudev-dev libhidapi-dev libwayland-dev libuvc-dev libavcodec-dev libopencv-dev libv4l-dev libcjson-dev libsdl2-dev libegl1-mesa-dev libxcb-glx0-dev
```

And build Monado itself:

```
git clone https://github.com/KhronosGroup/OpenXR-SDK.git
cd OpenXR-SDK
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -Bbuild
sudo ninja -C build install
```
However, I still get the same error:

```
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to determine active runtime file path for this environment
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
[2022.04.12-13.27.03:899][  0]LogHMD: Failed to enumerate extensions. Please check that you have a valid OpenXR runtime installed.
```

I still observe the same behavior of the scene rendering being rudimentary, the VR Preview being unavailable.

---

As a last attempt, I started the Unreal Editor from outside the Steam environment:

```
 ./Engine/Binaries/Linux/UnrealEditor '/home/bengt/Downloads/DFKI/git.ni.dfki.de/VR/VR.Frontend_5.0/VR_Frontend_5_0/VR_Frontend.uproject'
```

I still get an error about the driver having known issues and the same behavior in Unreal Engine.

**Comment by ARtSSt** [comment]
Any update were you ever able to get this to work?

**Comment by Bengt** [comment]
No, I never got this to work. I gave up and used Unity.

**Comment by wyattlrose** [comment]
Hey wanted to report this is still an ongoing issue, no solutions found on my end either.

**Comment by ARtSSt** [comment]
i fixed this on my end, for unreal you do not use the steam plugin, only the openXR plugin. Then go into the steam client and set it to be the default openXRruntime.  You may have to reinstall UE5 but i did not. install and tested on UE5.1 or 5.2, ubuntu 20.04 and 22.04 with kde.

**Comment by wyattlrose** [comment]
Oh that is awesome to hear! Its still not quite working for me here, where am I going wrong.
1. Every single VR plugin in Unreal Engine 5.1 is disabled except for the OpenXR plugin.
2. When I select SteamVR settings and check under the "Developer" tab, steamVR is the current Open XR Runtime.
3. I'm executing Unreal engine with a simple "./UnrealEditor"
Anything obvious I could be missing? Are you executing Unreal Editor using any additional args or do you have steamVR on any beta branch?

**Comment by ARtSSt** [comment]
I am out of town and can check in a week when i am home, but i believe I also had to make sure the steam client is set to linux and not proton in one of the developer settings.

**Comment by wyattlrose** [comment]
Solved it ! Tried running it within the steamVR runtime using the command and now it picks up the headset without issue:

`~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./UnrealEditor`

Thanks so much for the help, I'll see how my client is configured and maybe I can get this working outside of the steam runtime..

**Comment by ARtSSt** [comment]
great to hear glad I could help
It should be possible to use monado as the openXr runtime and ditch steam I just have not had time to mess with it as I was streaming to my headset and my server still relies on steams ovr drivers. But for local tethered use cases it likely is not hard.

**Comment by WhitleyStriber** [comment]
I'm having an issue like this, except that I am able to click VR Preview once. When I exit the VR Preview and try to launch it again, i get a "XR_ERROR_CALL_ORDER_INVALID" error in Terminal. Anyone have a similar issue?

**Comment by SinanAkkoyun** [comment]
@Bengt For me it also won't work. But how did you get Unity working?? (OpenXR only allows Windows build target, after installing OpenVR (SteamVR plugin), it always crashes on hitting "play")

**Comment by SinanAkkoyun** [comment]
@ARtSSt There is no other XR runtime in my settings, what program did you install to also have the OpenXR option?

**Comment by SinanAkkoyun** [comment]
@wyattlrose Hey, when I try the steam runtime, the VR preview has terrible performance, was that the same case for you?
